# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)

2.3.3


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
a=np.array([1,2,3],dtype=int64)
memory_size=a.size * a.itemsize

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_vector=np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vector=np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
vector=np.array([1,2,3,4,5])
reversed_vector=vector[::-1]
print(reversed_vector)

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
vector= np.arange(9)
matrix=vector.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
array=np.array([1,2,0,0,4,0])
indices=np.nonzero(array)
print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
identity_matrix=np.identity (3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
random_array=np.random.rand(3,3,3)
print(random_array)

[[[0.11201635 0.56287654 0.42617619]
  [0.09444296 0.82888566 0.53340789]
  [0.47327446 0.75744085 0.34450821]]

 [[0.11456954 0.17343549 0.52655044]
  [0.75678459 0.78354022 0.20353086]
  [0.61676741 0.05791718 0.55302806]]

 [[0.90534166 0.76259402 0.33129286]
  [0.55559105 0.89702928 0.83239923]
  [0.30846092 0.42778196 0.98687704]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
np.random.seed(0)
arr_10x10 = np.random.rand(10, 10)
print("10x10 array:\n", arr_10x10)
print("min =", arr_10x10.min())
print("max =", arr_10x10.max())

10x10 array:
 [[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
  0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606 0.0871293
  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443 0.63992102
  0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355
  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672 0.67063787
  0.21038256 0.1289263  0.31542835 0.36371077]
 [0.57019677 0.43860151 0.98837384 0.10204481 0.20887676 0.16130952
  0.65310833 0.2532916  0.46631077 0.24442559]
 [0.15896958 0.11037514 0.65632959 0.13818295 0.19658236 0.36872517
  0.82099323 0.09710128 0.83794491 0.09609841]
 [0.97645947 0.4686512  0.97676109 0.60484552 0.73926358 0.03918779
  0.28280696 0.12019656 0.2961402  0.11872772]
 [0.31798318 0.41426299 0.0641475  0.69247212 0.56660145 0.26538949


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
vec30 = np.random.rand(30)
print("\nvector (30):\n", vec30)
print("mean =", vec30.mean())


vector (30):
 [0.67781654 0.27000797 0.73519402 0.96218855 0.24875314 0.57615733
 0.59204193 0.57225191 0.22308163 0.95274901 0.44712538 0.84640867
 0.69947928 0.29743695 0.81379782 0.39650574 0.8811032  0.58127287
 0.88173536 0.69253159 0.72525428 0.50132438 0.95608363 0.6439902
 0.42385505 0.60639321 0.0191932  0.30157482 0.66017354 0.29007761]
mean = 0.5825186271316452


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)