In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
np.sort(a)

array([1, 2, 3, 4])

In [4]:
b=np.array([[1,2,3],[9,8,3],[7,6,4]])
print(b)

[[1 2 3]
 [9 8 3]
 [7 6 4]]


In [7]:
np.sort(b,axis=-1)

array([[1, 2, 3],
       [3, 8, 9],
       [4, 6, 7]])

In [6]:
np.sort(b,axis=None)

array([1, 2, 3, 3, 4, 6, 7, 8, 9])

In [9]:
#argsort
c=np.array([3,4,7,9,4])
print(c)

[3 4 7 9 4]


In [10]:
np.sort(c)

array([3, 4, 4, 7, 9])

In [11]:
np.argsort(c)

array([0, 1, 4, 2, 3])

In [12]:
e=np.array([1,2,3,4,5,6])


In [13]:
np.partition(e,4)

array([1, 2, 3, 4, 5, 6])