# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [2]:
arr=np.array([10,22,14,26,35])
value=20
nearest=arr[np.abs(arr-value).argmin()]
print(nearest)

22


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [3]:
a=np.array([[1,2,3]])
b=np.array([[4],[5],[6]])
it=np.nditer([a,b,None])
for x,y,z in it:
    z[...]=x+y
print(it.operands[2])

[[5 6 7]
 [6 7 8]
 [7 8 9]]


#### 63. Create an array class that has a name attribute (★★☆)

In [45]:
class NamedArray:
    def __init__(self, name, elements):
        self.name = name
        self.elements = np.array(elements)  

    def n_largest(self, n):
        """Return the n largest values in descending order"""
        return np.sort(self.elements)[-n:][::-1]

    def add(self, value):
        """Append a new value"""
        self.elements = np.append(self.elements, value)

    def __len__(self):
        return len(self.elements)

    def __getitem__(self, index):
        return self.elements[index]

    def __repr__(self):
        return f"NamedArray(name='{self.name}', elements={self.elements})" 
 

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [5]:
x = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 1, 1, 3])

np.add.at(x, indices, 1)
print(x)   

[2 4 3 5 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [6]:
X = np.array([1, 2, 3, 4])
I = np.array([0, 1, 1, 2])
F = np.zeros(4, dtype=int)

np.add.at(F, I, X)
print(F)   

[1 5 4 0]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [7]:
w, h = 4, 4
image = np.random.randint(0, 256, (w, h, 3), dtype=np.uint8)

colors = np.unique(image.reshape(-1, 3), axis=0)
print("Unique colors:", len(colors))

Unique colors: 16


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [8]:
arr_4d = np.random.rand(2, 3, 4, 5)

sum_result = arr_4d.sum(axis=(-2, -1))

print(f"Original shape: {arr_4d.shape}")
print(f"Result shape after sum: {sum_result.shape}")

Original shape: (2, 3, 4, 5)
Result shape after sum: (2, 3)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [9]:
D = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
# Vector S describing subset indices
S = np.array([0, 0, 1, 1, 1, 2, 2, 3, 3, 3])

# Use bincount to sum values within each subset
subset_sums = np.bincount(S, weights=D)

# Use bincount to count elements in each subset
subset_counts = np.bincount(S)

# Compute the mean
subset_means = subset_sums / subset_counts

print(f"Vector D: {D}")
print(f"Vector S (indices): {S}")
print(f"Means of subsets: {subset_means}")

Vector D: [ 10  20  30  40  50  60  70  80  90 100]
Vector S (indices): [0 0 1 1 1 2 2 3 3 3]
Means of subsets: [15. 40. 65. 90.]


#### 69. How to get the diagonal of a dot product? (★★★)

In [10]:

A = np.arange(9).reshape(3, 3)
B = A[::-1, :]  

dot_product = np.dot(A, B)
diagonal_result = np.diag(dot_product)


print(f"Matrix A:\n{A}")
print(f"\nMatrix B:\n{B}")
print(f"\nDiagonal of dot product (np.dot + np.diag): {diagonal_result}")

Matrix A:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Matrix B:
[[6 7 8]
 [3 4 5]
 [0 1 2]]

Diagonal of dot product (np.dot + np.diag): [ 3 42 99]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [11]:
# Original vector
original_vector = np.array([1, 2, 3, 4, 5])
zeros_to_add = 3

# Calculate the size of the new vector
new_size = len(original_vector) + (len(original_vector) - 1) * zeros_to_add

# Create a new array of zeros with the correct size
new_vector = np.zeros(new_size, dtype=original_vector.dtype)

# Place the original vector elements at the correct intervals
new_vector[::zeros_to_add + 1] = original_vector

print(f"Original vector: {original_vector}")
print(f"New vector: {new_vector}")

Original vector: [1 2 3 4 5]
New vector: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [12]:

arr_a = np.random.rand(5, 5, 3)
arr_b = np.random.rand(5, 5)

result = arr_a * arr_b[:, :, np.newaxis]

print(f"Shape of arr_a: {arr_a.shape}")
print(f"Shape of arr_b: {arr_b.shape}")
print(f"Shape of result: {result.shape}")

Shape of arr_a: (5, 5, 3)
Shape of arr_b: (5, 5)
Shape of result: (5, 5, 3)


#### 72. How to swap two rows of an array? (★★★)

In [13]:
# Create a sample array
arr = np.arange(9).reshape(3, 3)
print(f"Original array:\n{arr}")

# Swap row 0 and row 2
arr[[0, 2]] = arr[[2, 0]]

print(f"\nArray after swapping rows 0 and 2:\n{arr}")

Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Array after swapping rows 0 and 2:
[[6 7 8]
 [3 4 5]
 [0 1 2]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [14]:
triangles = np.random.randint(0, 100, (10, 3))
print(f"Sample triangles:\n{triangles}")

edges = np.concatenate([triangles[:, [0, 1]], triangles[:, [1, 2]], triangles[:, [2, 0]]])

edges.sort(axis=1)

unique_segments = np.unique(edges, axis=0)

print(f"\nUnique line segments:\n{unique_segments}")

Sample triangles:
[[54 91 39]
 [ 4 19 97]
 [73 22 19]
 [33 18 54]
 [36 86 73]
 [46 54 87]
 [25 14 62]
 [73 63 71]
 [23 69 13]
 [82 79  4]]

Unique line segments:
[[ 4 19]
 [ 4 79]
 [ 4 82]
 [ 4 97]
 [13 23]
 [13 69]
 [14 25]
 [14 62]
 [18 33]
 [18 54]
 [19 22]
 [19 73]
 [19 97]
 [22 73]
 [23 69]
 [25 62]
 [33 54]
 [36 73]
 [36 86]
 [39 54]
 [39 91]
 [46 54]
 [46 87]
 [54 87]
 [54 91]
 [63 71]
 [63 73]
 [71 73]
 [73 86]
 [79 82]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [15]:
C = np.array([0, 2, 0, 1, 3, 0])
numbers = np.arange(len(C))
A = np.repeat(numbers, C)

print(f"Original bincount array C: {C}")
print(f"Reconstructed array A: {A}")
print(f"Verifying with np.bincount(A): {np.bincount(A)}")

Original bincount array C: [0 2 0 1 3 0]
Reconstructed array A: [1 1 3 4 4 4]
Verifying with np.bincount(A): [0 2 0 1 3]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

window_size = 3

window = np.ones(window_size) / window_size

sliding_average = np.convolve(arr, window, mode='valid')

print(f"Original array: {arr}")
print(f"Sliding window averages: {sliding_average}")

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Sliding window averages: [2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [18]:

from numpy.lib.stride_tricks import as_strided

Z = np.arange(10)
window_size = 3

rows = len(Z) - window_size + 1
cols = window_size
stride = Z.strides[0]

result = as_strided(Z, shape=(rows, cols), strides=(stride, stride))

print(f"Original 1D array:\n{Z}")
print(f"\nResulting 2D array:\n{result}")

Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Resulting 2D array:
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [46]:
bool_arr = np.array([True, False, True])
np.logical_not(bool_arr, out=bool_arr)   # in-place
print(bool_arr) 

float_arr = np.array([1.5, -3.2, 0.0, 7.8])
np.negative(float_arr, out=float_arr)   # in-place
print(float_arr) 

[False  True False]
[-1.5  3.2 -0.  -7.8]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [20]:
# Sample data: sets of lines and points
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
P = np.random.uniform(-10, 10, (10, 2))

lines_vec = P1 - P0

# Vector from P0 to each point P
p_minus_p0 = P[:, np.newaxis, :] - P0[np.newaxis, :, :]

#2D cross product: (a.x * b.y) - (a.y * b.x)
cross_product = np.abs(p_minus_p0[:, :, 0] * lines_vec[np.newaxis, :, 1] -
                       p_minus_p0[:, :, 1] * lines_vec[np.newaxis, :, 0])

line_lengths = np.sqrt(np.sum(lines_vec**2, axis=1))

distances = cross_product / line_lengths[np.newaxis, :]

print("Distances (rows are points, columns are lines):\n", distances)

Distances (rows are points, columns are lines):
 [[10.95804087 16.30786495  5.11097867  6.24262376  5.28439654  9.32187518
  16.44319248  5.82922162  4.67131034  3.23981649]
 [ 7.1044199   9.81576804  7.39169045  3.89989709  6.38227588 10.14495289
   6.29142805  6.40328585  3.89356672  3.6247441 ]
 [11.97978552 16.21268234  0.52667157  1.37388078  0.41533194 12.0277619
  14.4805366   8.45396331  3.58118791  1.11499418]
 [ 8.51818405 12.6146433   0.99087892  1.55667122  0.27367251  9.17149246
  11.08458982  5.55497615  0.02042781  0.31164457]
 [ 8.43696325 11.52542441  5.39598008  2.61972588  4.69423843 10.72195875
   8.43037872  7.0230336   1.9222692   3.07053107]
 [ 5.20995512 11.15673596  6.17221051  9.97257486  7.75005996  3.25329648
  12.91417188  0.24357157  0.2822978   8.4082008 ]
 [ 5.77605673  9.77799109  2.13406975  1.75786808  0.76005499  6.88706214
   8.42920222  3.23780493  2.77516826  1.48784245]
 [ 1.00078762  2.95642655 12.30763841  5.72093897  9.8551939   5.93791415
   

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [21]:
# Sample data: sets of lines and points
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
P = np.random.uniform(-10, 10, (10, 2))

# Vector for each line
lines_vec = P1 - P0

# Vector from P0 to each point P
p_minus_p0 = P[:, np.newaxis, :] - P0[np.newaxis, :, :]

#2D cross product: (a.x * b.y) - (a.y * b.x)
cross_product = np.abs(p_minus_p0[:, :, 0] * lines_vec[np.newaxis, :, 1] -
                       p_minus_p0[:, :, 1] * lines_vec[np.newaxis, :, 0])

# Length of each line vector
line_lengths = np.sqrt(np.sum(lines_vec**2, axis=1))

distances = cross_product / line_lengths[np.newaxis, :]

print("Distances (rows are points, columns are lines):\n", distances)

Distances (rows are points, columns are lines):
 [[4.61257007e-01 1.58825371e-01 2.01380888e-01 1.15312389e+01
  1.63266455e+00 3.26423872e+00 3.57957222e+00 6.19891735e+00
  3.55429537e+00 1.85594610e+00]
 [3.76901076e+00 2.34182788e+00 4.09980236e+00 5.82525992e+00
  1.14965692e+01 5.24791802e+00 6.04854953e+00 6.33175830e-03
  4.09268618e+00 3.31743665e+00]
 [5.20353297e+00 3.99530858e+00 2.16588298e+00 4.63894398e+00
  1.09990422e+01 5.69604414e+00 4.10546584e+00 1.81305896e+00
  5.91777198e+00 1.39415246e+00]
 [1.22611768e+01 1.27104358e+01 9.69414549e+00 6.58276140e-01
  5.78332729e+00 6.14422134e+00 7.45706645e+00 1.35161148e+01
  1.60801306e+01 9.81059746e+00]
 [5.94691088e+00 4.61297798e+00 4.27259200e-02 1.78046451e+01
  5.37966391e+00 1.06352589e+01 4.55933657e+00 8.35382928e+00
  3.85899684e-01 3.59858878e+00]
 [5.17404733e+00 4.36989471e+00 1.61910510e+00 1.65634783e+01
  2.55772318e+00 8.43292432e+00 5.74833766e+00 6.18558783e+00
  4.83273877e-02 4.50759264e+00]
 [2.96288

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [22]:
def extract_subpart(arr, center_point, shape, fill=0):
    
    arr_shape = np.array(arr.shape)
    sub_shape = np.array(shape)
    center = np.array(center_point)

    padding = np.maximum(0, (sub_shape // 2) - center)
    padding = np.vstack([padding, np.maximum(0, center + (sub_shape // 2) + 1 - arr_shape)]).T
    
    # Pad the array
    padded_arr = np.pad(arr, padding, mode='constant', constant_values=fill)
    
    # Recalculate the center point in the padded array
    padded_center = center + padding[:, 0]
    
    # Calculate the slicing indices for the padded array
    start_idx = padded_center - (sub_shape // 2)
    end_idx = start_idx + sub_shape
    
    # Slice and return the result
    slices = tuple(slice(start, end) for start, end in zip(start_idx, end_idx))
    return padded_arr[slices]

arr = np.arange(25).reshape(5, 5)
print("Original array:\n", arr)

# Extract a 3x3 subpart centered at (2,2)
subpart1 = extract_subpart(arr, (2, 2), (3, 3))
print("\nSubpart centered at (2,2):\n", subpart1)

# Extract a 3x3 subpart centered at (0,0) with padding
subpart2 = extract_subpart(arr, (0, 0), (3, 3), fill=-1)
print("\nSubpart centered at (0,0) with padding:\n", subpart2)

Original array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Subpart centered at (2,2):
 [[ 6  7  8]
 [11 12 13]
 [16 17 18]]

Subpart centered at (0,0) with padding:
 [[-1 -1 -1]
 [-1  0  1]
 [-1  5  6]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [23]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

window_size = 4

rows = len(Z) - window_size + 1
cols = window_size
stride = Z.strides[0]

R = as_strided(Z, shape=(rows, cols), strides=(stride, stride))

print(f"Original array Z:\n{Z}")
print(f"\nResulting array R:\n{R}")

Original array Z:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Resulting array R:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [24]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [5, 7, 9]]) 

rank = np.linalg.matrix_rank(A)

print(f"Matrix A:\n{A}")
print(f"Rank of the matrix: {rank}")

Matrix A:
[[1 2 3]
 [4 5 6]
 [5 7 9]]
Rank of the matrix: 2


#### 83. How to find the most frequent value in an array?

In [25]:
Z = np.random.randint(0, 10, 50)

counts = np.bincount(Z)

most_frequent_value = np.argmax(counts)

print(f"Original array:\n{Z}")
print(f"Counts of each value: {counts}")
print(f"The most frequent value is: {most_frequent_value}")

Original array:
[2 5 5 5 0 8 9 3 3 7 9 7 7 9 0 2 8 2 9 2 8 3 6 8 7 9 9 1 8 5 4 2 5 3 9 1 4
 6 0 6 3 4 6 1 6 5 5 4 1 5]
Counts of each value: [3 4 5 5 4 8 5 4 5 7]
The most frequent value is: 5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [26]:
matrix = np.random.rand(10, 10)
block_size = 3

rows = matrix.shape[0] - block_size + 1
cols = matrix.shape[1] - block_size + 1
strides = matrix.strides + matrix.strides

blocks = as_strided(matrix, shape=(rows, cols, block_size, block_size), strides=strides)

print(f"Original 10x10 matrix:\n{matrix}")
print(f"\nShape of the extracted blocks array: {blocks.shape}")
print(f"\nExample of the first block (top-left):\n{blocks[0, 0]}")

Original 10x10 matrix:
[[0.78005029 0.9219708  0.00179828 0.36704418 0.17209149 0.18248692
  0.10254624 0.69821612 0.06997987 0.73380123]
 [0.5351124  0.65952061 0.8922823  0.62616376 0.18287363 0.4749778
  0.17404084 0.14626628 0.79508227 0.64284582]
 [0.95868922 0.95635988 0.16668669 0.30973793 0.21030536 0.27740061
  0.41348879 0.89902871 0.1452067  0.81154135]
 [0.06256525 0.68750996 0.77425738 0.14057417 0.77334715 0.04702333
  0.41657594 0.82018091 0.41563521 0.47575235]
 [0.51795496 0.64298792 0.6649566  0.48725116 0.22414559 0.26192884
  0.9514739  0.23979869 0.51423702 0.05331799]
 [0.43643915 0.5666917  0.64870174 0.91578682 0.49818865 0.08477743
  0.78547429 0.60006446 0.23701974 0.8488201 ]
 [0.26486475 0.49737844 0.47059515 0.20140812 0.41243706 0.0820889
  0.06852299 0.88599045 0.06822606 0.79596788]
 [0.3768914  0.74041484 0.08690294 0.34546194 0.87721434 0.52087714
  0.65021937 0.31600045 0.30619572 0.06968381]
 [0.20047324 0.28637526 0.78726926 0.83434519 0.88026102 0.

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [27]:
class SymmetricArray(np.ndarray):
    def _setitem_(self, key, value):
        i, j = key
        super()._setitem_((i, j), value)
        super()._setitem_((j, i), value)

    def _new_(cls, *args, **kwargs):
        obj = np.ndarray._new_(cls, *args, **kwargs)
        return obj
    
Z = np.zeros((3, 3), dtype=int).view(SymmetricArray)
print("Original symmetric array:\n", Z)

Z[0, 1] = 5
Z[2, 0] = 10

print("\nArray after setting Z[0, 1] and Z[2, 0]:\n", Z)

Original symmetric array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Array after setting Z[0, 1] and Z[2, 0]:
 [[ 0  5  0]
 [ 0  0  0]
 [10  0  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [28]:
# Define p, n
p = 5
n = 4

# Create p matrices of shape (n,n)
matrices = np.random.rand(p, n, n)

# Create p vectors of shape (n,1)
vectors = np.random.rand(p, n, 1)

result = np.einsum('pij, pjk->pik', matrices, vectors)

final_result = np.sum(result, axis=0)

print(f"Shape of matrices: {matrices.shape}")
print(f"Shape of vectors: {vectors.shape}")
print(f"Shape of the final sum of products: {final_result.shape}")

Shape of matrices: (5, 4, 4)
Shape of vectors: (5, 4, 1)
Shape of the final sum of products: (4, 1)


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [29]:
# Create a sample 16x16 array
arr = np.random.randint(0, 10, (16, 16))
block_size = 4

# Reshape the array to group the blocks
block_sum = arr.reshape(
    arr.shape[0] // block_size, block_size,
    arr.shape[1] // block_size, block_size
).sum(axis=(1, 3))

print(f"Original 16x16 array:\n{arr}")
print(f"\nShape of the block-sum array: {block_sum.shape}")
print(f"\nResulting 4x4 array of block sums:\n{block_sum}")

Original 16x16 array:
[[9 1 6 3 9 7 9 7 2 9 7 6 0 9 3 9]
 [5 7 9 2 6 7 3 5 7 3 7 9 2 0 0 6]
 [5 3 4 1 5 8 7 6 0 0 6 9 3 3 0 4]
 [9 8 3 7 7 6 7 0 5 6 9 4 8 6 4 0]
 [7 1 6 8 2 2 3 3 2 4 0 2 0 1 9 7]
 [2 4 8 8 3 9 9 4 7 1 4 8 2 2 8 3]
 [6 3 5 7 5 6 0 1 2 1 8 4 9 2 1 6]
 [6 0 2 9 2 6 9 6 9 2 9 8 3 2 5 4]
 [1 6 3 9 4 4 5 5 9 4 3 3 0 4 4 8]
 [6 3 9 6 9 4 6 3 8 4 8 2 9 5 0 7]
 [5 8 7 4 1 1 5 8 7 0 9 3 3 0 5 0]
 [9 8 4 0 3 4 0 0 0 7 8 3 0 4 0 7]
 [5 3 2 8 1 5 6 9 2 7 2 4 4 4 4 4]
 [0 9 6 6 1 6 3 0 5 1 7 1 8 2 1 7]
 [6 5 2 3 6 1 5 6 5 0 0 8 0 6 2 5]
 [7 8 8 6 4 6 0 1 9 2 6 4 5 1 6 5]]

Shape of the block-sum array: (4, 4)

Resulting 4x4 array of block sums:
[[82 99 89 57]
 [82 70 71 64]
 [88 62 78 56]
 [84 60 63 64]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [30]:
def game_of_life_step(grid):
    
    rows, cols = grid.shape
    padded_grid = np.pad(grid, 1, mode='wrap')
    
    kernel = np.array([[1, 1, 1], [1, 0, 1], [1, 1, 1]])
    neighbors = np.sum(
        [np.roll(np.roll(padded_grid, i, axis=0), j, axis=1)
         for i in [-1, 0, 1] for j in [-1, 0, 1] if (i,j) != (0,0)],
        axis=0
    )[1:-1, 1:-1]
    
    new_grid = grid.copy()
    
    survive = (grid == 1) & ((neighbors == 2) | (neighbors == 3))
    
    birth = (grid == 0) & (neighbors == 3)
    
    new_grid[:] = 0
    new_grid[survive | birth] = 1
    
    return new_grid

# Example
grid = np.zeros((10, 10), dtype=int)
grid[1, 2] = 1
grid[2, 3] = 1
grid[3, 1:4] = 1  # A "glider"
print("Initial grid:\n", grid)

for i in range(5):
    grid = game_of_life_step(grid)
    print(f"\nStep {i+1}:\n", grid)

Initial grid:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Step 1:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Step 2:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Step 3:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Step 4:
 [[0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [43]:
arr = np.array([10, 4, 8, 15, 3, 20])
n = 3

largest_n = np.sort(arr)[-n:][::-1]
print(largest_n)  

[20 15 10]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [32]:
# Sample vectors
v1 = np.array([1, 2, 3])
v2 = np.array(['a', 'b'])
v3 = np.array([10, 20])

# Use meshgrid to create grids of all combinations
grid = np.meshgrid(v1, v2, v3)

# Stack the results to get the Cartesian product
cartesian_product = np.vstack([x.ravel() for x in grid]).T

print(f"The Cartesian product:\n{cartesian_product}")

The Cartesian product:
[['1' 'a' '10']
 ['1' 'a' '20']
 ['2' 'a' '10']
 ['2' 'a' '20']
 ['3' 'a' '10']
 ['3' 'a' '20']
 ['1' 'b' '10']
 ['1' 'b' '20']
 ['2' 'b' '10']
 ['2' 'b' '20']
 ['3' 'b' '10']
 ['3' 'b' '20']]


#### 91. How to create a record array from a regular array? (★★★)

In [33]:
# Sample regular array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Define the structured data type
dtype = [('x', int), ('y', int), ('z', int)]

# Create the record array
record_array = arr.ravel().view(dtype=dtype).reshape(arr.shape[0])

print("Original array:\n", arr)
print("\nRecord array:\n", record_array)
print("\nAccessing a field (e.g., 'x'):", record_array['x'])

Original array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Record array:
 [(10, 20, 30) (40, 50, 60) (70, 80, 90)]

Accessing a field (e.g., 'x'): [10 40 70]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [34]:
# Sample regular array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Define the structured data type
# Each tuple defines a field: (field_name, data_type)
dtype = [('x', int), ('y', int), ('z', int)]

record_array = arr.ravel().view(dtype=dtype).reshape(arr.shape[0])

print("Original array:\n", arr)
print("\nRecord array:\n", record_array)
print("\nAccessing a field (e.g., 'x'):", record_array['x'])

Original array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Record array:
 [(10, 20, 30) (40, 50, 60) (70, 80, 90)]

Accessing a field (e.g., 'x'): [10 40 70]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [35]:
# Create sample arrays
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 3))

# Sort each row for consistent comparison
A.sort(axis=1)
B.sort(axis=1)

# Find unique rows in B to avoid redundant checks
unique_B_rows = np.unique(B, axis=0)

# Check which rows of A are in B
is_in_B = np.all(A[:, None, :] == unique_B_rows[None, :, :], axis=2)
result = np.any(is_in_B, axis=1)

print(f"Array A:\n{A}")
print(f"\nArray B:\n{B}")
print(f"\nBoolean mask for rows of A present in B:\n{result}")

Array A:
[[2 2 4]
 [0 3 4]
 [3 3 4]
 [1 2 4]
 [2 3 3]
 [0 2 3]
 [0 2 4]
 [2 4 4]]

Array B:
[[1 2 4]
 [1 1 3]]

Boolean mask for rows of A present in B:
[False False False  True False False False False]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [36]:
# Create a sample 10x3 matrix
Z = np.random.randint(0, 3, (10, 3))
print(f"Original matrix:\n{Z}")

# Find rows where min and max values are different
unequal_rows = Z[Z.max(axis=1) != Z.min(axis=1)]

print(f"\nRows with unequal values:\n{unequal_rows}")

Original matrix:
[[2 2 2]
 [0 1 0]
 [1 2 1]
 [0 0 2]
 [2 0 1]
 [2 2 1]
 [0 0 1]
 [1 2 0]
 [2 0 0]
 [0 2 1]]

Rows with unequal values:
[[0 1 0]
 [1 2 1]
 [0 0 2]
 [2 0 1]
 [2 2 1]
 [0 0 1]
 [1 2 0]
 [2 0 0]
 [0 2 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [37]:
# Sample integer vector
I = np.array([0, 1, 2, 3, 4, 5, 6, 7], dtype=np.uint8)

binary_matrix = np.unpackbits(I[:, np.newaxis], axis=1)

print(f"Original vector:\n{I}")
print(f"\nBinary representation (matrix):\n{binary_matrix}")

Original vector:
[0 1 2 3 4 5 6 7]

Binary representation (matrix):
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [38]:
# Create a sample 2D array with duplicate rows
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [1, 2, 3],
                [7, 8, 9],
                [4, 5, 6]])
print(f"Original array:\n{arr}")

unique_rows = np.unique(arr, axis=0)

print(f"\nUnique rows:\n{unique_rows}")

Original array:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]

Unique rows:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [39]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# 1. Inner Product (Dot Product)
# 'i, i -> ' sums over the product of elements with the same index
inner_product = np.einsum('i,i->', A, B)
print(f"Inner product (einsum): {inner_product}")

# 2. Outer Product
# 'i, j -> ij' creates a matrix where the element at (i,j) is A[i]*B[j]
outer_product = np.einsum('i,j->ij', A, B)
print(f"Outer product (einsum):\n{outer_product}")

# 3. Sum of elements
# 'i -> ' sums over all elements of the vector
total_sum_A = np.einsum('i->', A)
print(f"Sum of A (einsum): {total_sum_A}")

# 4. Element-wise Multiplication (Hadamard product)
# 'i, i -> i' multiplies elements with the same index and keeps the vector shape
elementwise_mul = np.einsum('i,i->i', A, B)
print(f"Element-wise multiplication (einsum): {elementwise_mul}")

Inner product (einsum): 32
Outer product (einsum):
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum of A (einsum): 6
Element-wise multiplication (einsum): [ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [40]:
# Sample path data (X, Y vectors)
X = np.linspace(0, 10, 20)
Y = np.sin(X)

# Compute the distance between each point
distances = np.sqrt(np.diff(X)*2 + np.diff(Y)*2)

# Compute the cumulative distance
cumulative_dist = np.cumsum(distances)
cumulative_dist = np.insert(cumulative_dist, 0, 0) # Add 0 at the start

# Define the number of equidistant samples you want
num_samples = 10

# Create the new equidistant sample points
equidistant_points = np.linspace(0, cumulative_dist[-1], num_samples)

# Use linear interpolation to find the (X, Y) coordinates
X_equidistant = np.interp(equidistant_points, cumulative_dist, X)
Y_equidistant = np.interp(equidistant_points, cumulative_dist, Y)

print(f"Original X points: {X}")
print(f"Original Y points: {Y}")
print(f"\nEquidistant X samples: {X_equidistant}")
print(f"Equidistant Y samples: {Y_equidistant}")

Original X points: [ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
Original Y points: [ 0.          0.50235115  0.86872962  0.99996678  0.86054034  0.48818921
 -0.01630136 -0.5163796  -0.87668803 -0.99970104 -0.85212237 -0.47389753
  0.03259839  0.53027082  0.88441346  0.99916962  0.84347795  0.4594799
 -0.04888676 -0.54402111]

Equidistant X samples: [ 0.          0.70235882  1.50791763  3.34863279  4.85511865  5.64711613
  6.34530064  7.05248836  7.87260892 10.        ]
Equidistant Y samples: [ 0.          0.62489807  0.98225547 -0.19753087 -0.96653636 -0.57619953
  0.06050349  0.6718315   0.99434492 -0.54402111]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [41]:

n = 10
X = np.random.randint(0, 10, (20, 5))
X[0] = [1, 2, 3, 4, 0]
X[1] = [1, 2, 3, 4, 1]
X[2] = [-1, 2, 3, 6, 0]

is_non_negative = np.all(X >= 0, axis=1)

sums_equal_n = np.sum(X, axis=1) == n

valid_rows = X[is_non_negative & sums_equal_n]

print(f"Original array:\n{X}")
print(f"\nValid rows (sum to {n} and are non-negative):\n{valid_rows}")

Original array:
[[ 1  2  3  4  0]
 [ 1  2  3  4  1]
 [-1  2  3  6  0]
 [ 8  2  1  6  5]
 [ 2  3  9  7  7]
 [ 4  6  3  4  8]
 [ 8  9  3  2  4]
 [ 3  7  3  9  9]
 [ 3  3  2  7  4]
 [ 7  4  9  2  2]
 [ 8  1  8  6  9]
 [ 7  9  7  0  1]
 [ 5  9  2  8  6]
 [ 7  7  6  3  1]
 [ 6  2  0  9  2]
 [ 2  8  2  6  5]
 [ 2  4  3  3  7]
 [ 5  4  2  1  5]
 [ 8  1  6  3  7]
 [ 4  3  2  0  1]]

Valid rows (sum to 10 and are non-negative):
[[1 2 3 4 0]
 [4 3 2 0 1]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [42]:
# Sample 1D array
X = np.random.randn(100) 

# Number of bootstrap samples
N = 1000

# Perform the bootstrapping
bootstrapped_means = []
for _ in range(N):
    # Resample with replacement
    sample = np.random.choice(X, size=len(X), replace=True)
    
    # Compute the mean of the sample
    bootstrapped_means.append(np.mean(sample))

# Convert to a NumPy array for easy percentile calculation
bootstrapped_means = np.array(bootstrapped_means)

# Compute the 95% confidence interval using percentiles
lower_bound = np.percentile(bootstrapped_means, 2.5)
upper_bound = np.percentile(bootstrapped_means, 97.5)

print(f"Original mean: {np.mean(X):.4f}")
print(f"Bootstrapped 95% Confidence Interval for the mean: ({lower_bound:.4f}, {upper_bound:.4f})")

Original mean: 0.1242
Bootstrapped 95% Confidence Interval for the mean: (-0.0586, 0.3037)
